"""039_create_terminology

Revision ID: 25cbc85766fd
Revises: fc23c4f3e755
Create Date: 2025-08-25 11:38:32.990973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25cbc85766fd'
down_revision = 'fc23c4f3e755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #todo:注释这行
    # 原代码：op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # 修改为：
    try:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
        print("Vector extension created successfully")
    except Exception as e:
        print(f"Warning: Could not create vector extension: {e}")
        print("Continuing migration without vector extension...")

    op.create_table('terminology',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('pid', sa.BigInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminology')
    # ### end Alembic commands ###
